# https://taskfile.dev
version: "3"

includes:
  argocd:
    taskfile: tasks/argocd
    internal: true

  utils:
    taskfile: tasks/utils
    internal: true

  dev:
    taskfile: tasks/dev
    internal: true

dotenv: [".envrc", ".env"]

vars:
  # determines what type of local cluster gets deployed.
  # Currently the only options are "kind", "k3d" or "talos"
  CLUSTER_TYPE: '{{ .CLUSTER_TYPE | default "k3d" }}'

interval: 500ms

silent: true

tasks:
  default: task --list

  up:
    desc: "Deploy entire local development environment."
    # TODO: write a concise summary
    cmds:
      - task: dev:up
      - task: create-aliasses

  destroy:
    desc: "Destroy entire local development environment."
    aliases: [down, destroy, get-rekt]
    cmds:
      - task: dev:destroy

  sync-local:
    desc: "This task watches local changes in the service directory and applies them to the local cluster."
    cmds:
      - task: dev:sync-local

  sync:
    desc: "This task triggers a normal sync for one or more services."
    cmds:
      - task: dev:sync-apps

  sync-all:
    desc: "This task triggers a sync for all services."
    cmds:
      - task: dev:sync-all-apps

  create-aliasses:
    desc: "Create kubectl aliasses"
    cmds:
      - echo "" >> /home/vscode/.bashrc
      - echo "alias k='kubectl'" >> /home/vscode/.bashrc
      - echo "alias kns='kubens'" >> /home/vscode/.bashrc
      - echo "alias kgp='kubectl get pods'" >> /home/vscode/.bashrc
      - echo "alias kgs='kubectl get svc'" >> /home/vscode/.bashrc
      - echo "alias kgn='kubectl get nodes'" >> /home/vscode/.bashrc
      - echo "alias keti='kubectl exec -ti'" >> /home/vscode/.bashrc
      - source /home/vscode/.bashrc
