# https://taskfile.dev

version: "3"

includes:
  argocd: ../argocd
  k3d: ../k3d
  talos: ../talos
  utils: ../utils

interval: 1s

tasks:
  up:
    requires:
      vars:
        - PERSONAL_ACCESS_TOKEN
        - CLUSTER_TYPE

    preconditions:
      - sh: '[[ "{{.CLUSTER_TYPE}}" =~ "^(k3d|talos)$" ]]'
        msg: "Unsupported CLUSTER_TYPE: {{.CLUSTER_TYPE}}"

    cmds:
      # Create cluster based on type
      - task: create-k3d-cluster
      - task: create-talos-cluster

      # switch to argocd as the default namespace, this helps with argocd cli's core mode.
      - cmd: gum log --level info $(kubectl config set-context --current --namespace argocd)
      - cmd: gum log --level info $(argocd login --core)

      - task: argocd:bootstrap
        vars:
          ARGOCD_REPO_USERNAME: "{{.USERNAME}}"
          ARGOCD_REPO_PASSWORD: "{{.PERSONAL_ACCESS_TOKEN}}"
          ARGOCD_REPO_URL: "{{.ARGOCD_REPO_URL}}"
          ARGOCD_BOOTSTRAP_DIR: "{{.ARGOCD_BOOTSTRAP_DIR}}"

      # # Deploy bootstrap applications
      - task: sync-bootstrap

      - cmd: gum log --level info "Local deployment complete."

  create-k3d-cluster:
    status:
      - '! [[ "{{.CLUSTER_TYPE}}" == "k3d" ]]'
    cmds:
      - task: k3d:create
        vars:
          K3D_CONFIG: k3d-config.yaml

  create-talos-cluster:
    desc: "Wrapper task that will only execute if the CLUSTER_TYPE matches"
    status:
      - '! [[ "{{.CLUSTER_TYPE}}" == "talos" ]]'
    cmds:
      - task: talos:create

  destroy:
    cmds:
      - task: k3d:delete
        vars:
          K3D_CONFIG: k3d-config.yaml
      - task: talos:delete

  sync:
    deps:
      - task: argocd:check-tools
    requires:
      vars:
        - ARGOCD_APPLICATIONS
    cmds:
      - for: { var: ARGOCD_APPLICATIONS }
        cmd: |
          argocd app terminate-op {{.ITEM}} 2> /dev/null || true
          gum log --level=info "Operations terminated for {{.ITEM}}"
          gum spin --show-error --title "Syncing {{.ITEM}}..." -- argocd app sync --server-side --prune {{.ITEM}} {{.ARGOCD_ARGS}} {{.CLI_ARGS}}
          gum log --level=info "{{.ITEM}} synced"

  sync-apps:
    deps:
      - task: argocd:check-tools
    vars:
      ARGOCD_ARGS:
        sh: if gum confirm 'Enable async?' ; then echo "--async" ; fi
      ARGOCD_APPLICATIONS:
        sh: gum choose --height=15 --no-limit --header="Choose the services to deploy:" <<<$(argocd app list --output name)
    preconditions:
      - sh: '[[ -n "{{.ARGOCD_APPLICATIONS}}" ]]'
        msg: "Unable to list ArgoCD Applications or no Applications present."
    cmds:
      - task: sync
        vars:
          ARGOCD_APPLICATIONS: "{{.ARGOCD_APPLICATIONS}}"
          ARGOCD_ARGS: "{{.ARGOCD_ARGS}}"

  sync-local:
    deps:
      - task: argocd:check-tools
    vars:
      SERVICE_NAME:
        # this command relies on the find implementation to return paths like ./some-service/dev/
        sh: 'find -maxdepth 2 -type d -name dev | cut -d / -f 2 | gum filter --header="Choose a service:"'
      CLUSTER_NAME:
        sh: 'ls {{.SERVICE_NAME}}/dev | gum filter --header="Choose a target cluster:"'
      NAMESPACE:
        sh: 'ls {{.SERVICE_NAME}}/dev/{{.CLUSTER_NAME}} | gum filter --header="Choose a namespace:"'

      APP_KUBERNETES_IO_INSTANCE: "{{.SERVICE_NAME}}-dev-{{.CLUSTER_NAME}}"
      MANIFEST_PATH: "{{.SERVICE_NAME}}/dev/{{.CLUSTER_NAME}}/{{.NAMESPACE}}"
    label: "{{.APP_KUBERNETES_IO_INSTANCE}}"
    cmds:
      - cmd: |
          find . {{.MANIFEST_PATH}} -type f -iname '*.yaml' | entr -c \
            argocd app sync \
              --server-side \
              --prune \
              --selector app.kubernetes.io/instance={{ .APP_KUBERNETES_IO_INSTANCE }} \
              --local-repo-root . \
              --local {{.MANIFEST_PATH}} \
              {{.CLI_ARGS}}

  sync-bootstrap:
    deps:
      - task: argocd:check-tools
    vars:
      ARGOCD_APPLICATIONS:
        sh: echo 'argocd/local-path-provisioner-dev-talos-local-path-storage argocd/ingress-nginx-dev-talos-ingress-nginx argocd/cert-manager-dev-talos-cert-manager'
    cmds:
      - cmd: |
          for app in {{.ARGOCD_APPLICATIONS}}; do
            argocd login --core
            while ! argocd app get $app &> /dev/null; do
              gum spin --show-output --title "Waiting for $app to be available..." -- sleep 5
            done
            gum log --level=info "$app is available"
          done
      - task: sync
        vars:
          ARGOCD_APPLICATIONS: "{{.ARGOCD_APPLICATIONS}}"
