# https://taskfile.dev

version: "3"

includes:
  utils: ../utils

tasks:
  bootstrap:
    desc: "Deploy ArgoCD and configure repositories"
    requires:
      vars:
        - ARGOCD_REPO_PASSWORD
        - ARGOCD_REPO_URL
        - ARGOCD_BOOTSTRAP_DIR
    dir: "{{.ARGOCD_BOOTSTRAP_DIR}}"
    cmds:
      # Create namespace and secrets
      - cmd: kubectl apply -f namespace.yaml --server-side
      - task: create-repo-credentials-secret
        vars:
          ARGOCD_REPO_PASSWORD: "{{.ARGOCD_REPO_PASSWORD}}"
          ARGOCD_REPO_URL: "{{.ARGOCD_REPO_URL}}"

      # Initial apply will fail because of some missing CRDs
      - cmd: gum spin --title "Applying initial ArgoCD manifests..." -- kustomize build --enable-helm . | kubectl apply --server-side --force-conflicts -f - >/dev/null 2>&1
        ignore_error: true

      - task: utils:wait-for
        vars:
          GUM_SPIN_TITLE: "Waiting for ArgoCD's CRDs to be established..."
          CONDITION: established
          RESOURCE: "crds/applications.argoproj.io crds/applicationsets.argoproj.io crds/appprojects.argoproj.io"
          NAMESPACE: argocd

      - task: utils:wait-for
        vars:
          GUM_SPIN_TITLE: "Waiting for ArgoCD's Application controller to become ready..."
          CONDITION: ready
          RESOURCE: pod/argocd-application-controller-0
          NAMESPACE: argocd

      # let this one fail too because of service monitors. Will fix itself after the applicationsets
      # have been applied.
      - cmd: gum spin --title "Final ArgoCD manifests application..." -- kustomize build --enable-helm . | kubectl apply --server-side --force-conflicts -f - >/dev/null 2>&1
        ignore_error: true

  create-repo-credentials-secret:
    internal: true
    requires:
      vars:
        - ARGOCD_REPO_PASSWORD
        - ARGOCD_REPO_URL
    cmds:
      - task: utils:wait-for
        vars:
          GUM_SPIN_TITLE: "Waiting for argocd namespace..."
          RESOURCE: namespace/argocd
          CONDITION: exists
      - cmd: |
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: git-credentials
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repo-creds
          stringData:
            url: {{.ARGOCD_REPO_URL}}
            username: {{.ARGOCD_REPO_USERNAME}}
            password: {{.ARGOCD_REPO_PASSWORD}}
          EOF

  check-tools:
    preconditions:
      - sh: command -v argocd > /dev/null
        msg: "Install argocd CLI: https://argo-cd.readthedocs.io/en/stable/cli_installation/"
      - sh: command -v kubectl > /dev/null
        msg: "Install kubectl: https://downloadkubernetes.com/"
      - sh: command -v gum > /dev/null
        msg: "Install gum: https://github.com/charmbracelet/gum"
      - sh: command -v yq > /dev/null
        msg: "Install yq: https://github.com/mikefarah/yq"
